# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.1-node-browsers

    working_directory: ~/repo
    environment:
      JEKYLL_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      JOB_RESULTS_PATH: run-results

    steps:
    - checkout

    - run:
        name: "Test Markdown Files"
        command: |
          wget https://github.com/felicianotech/md-proofer/releases/download/v0.1.0/md-proofer-v0.1.0-linux-amd64.tar.gz
          tar xfz md-proofer-v*.tar.gz
          sudo chmod +x ./md-proofer
          echo "Test Markdown files"
          echo "===================================================================================="
          ./md-proofer lint .

    - restore_cache:
        keys:
        - v4-quintsys-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - v4-quintsys-

    - run:
        name: "Install Ruby dependencies"
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

    - save_cache:
        paths:
        - vendor/bundle
        key: v4-quintsys-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

    - run:
        name: "Build Jekyll"
        command: bundle exec jekyll build --verbose

    - run:
        name: "Test Html"
        command: bundle exec htmlproofer ./_site --check-html --disable-external

    - run:
        name: "Install Firebase Tools"
        command: npm install --save-dev firebase-tools

    - run:
        name: "Deploy Master to Firebase"
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN