# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
    environment:
      JEKYLL_ENV: production
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      JEKYLL_PATH: ~/quintsys-web/jekyll
    working_directory: ~/quintsys-web
    steps:
      - checkout
      - run ls
#      - restore_cache:
#          keys:
#            - v2-gems-{{ .Branch }}-{{ checksum "jekyll/Gemfile.lock" }}
#            - v2-gems-{{ .Branch }}
#            - v2-gems
#      - run:
#          name: "Bundle Install"
#          command: |
#            cd $JEKYLL_PATH
#            bundle check || bundle install
#      - save_cache:
#          key: v2-gems-{{ .Branch }}-{{ checksum "jekyll/Gemfile.lock" }}
#          paths:
#            - $BUNDLE_PATH
#      - run:
#          name: "Build the Jekyll site"
#          command: |
#            cd $JEKYLL_PATH
#            bundle exec jekyll build
#      - run:
#          name: "Test with HTMLproofer"
#          command: |
#            cd $JEKYLL_PATH
#            bundle exec htmlproofer _site --check-favicon --check-html --disable-external --empty-alt-ignore
#      - store_artifacts:
#          path: $JEKYLL_PATH/_site
#          destination: quintsys-web
#      - persist_to_workspace:
#          root: $JEKYLL_PATH
#          paths:
#            - _site
  deploy:
    docker:
      - image: circleci/node:10.10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Install firebase-tools"
          command: yarn add firebase-tools --dev
      - run:
          name: "Deploy to Firebase if tests pass and branch is Master"
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only:
#                - master
