# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/node:2.5.1-node
    working_directory: ~/repo
    environment:
      JEKYLL_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      JOB_RESULTS_PATH: run-results
    steps:
    # Git checkout
    - checkout

    # Ruby Gems
    - restore_cache:
        keys:
        - v1-gems-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - v1-gems-{{ .Branch }}
        - v1-gems
    - run:
        name: "Install ruby gems"
        command: |
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
          bundle clean
    - save_cache:
        paths:
        - vendor/bundle
        key: v1-gems-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

    - run:
        name: "Create results directory"
        command: mkdir -p $JOB_RESULTS_PATH

    # Build it
    - run:
        name: "Build Jekyll"
        command: bundle exec jekyll build 2>&1 | tee $JOB_RESULTS_PATH/build-results.txt

    # Tests
    - run:
        name: "Test Html"
        command: bundle exec htmlproofer _site --check-favicon --check-html --disable-external --empty-alt-ignore | tee $JOB_RESULTS_PATH/htmlproofer-results.txt

    - store_artifacts:
        path: _site/
        destination: _site

    - store_artifacts:
        path: run-results/
        destination: run-results

    - persist_to_workspace:
        root: ~/repo/_site
        paths:
        - _site
  deploy:
    docker:
    - image: circleci/node:10.10
    steps:
    - attach_workspace:
        at: ./
    - run:
        name: "Install firebase-tools"
        command: yarn add firebase-tools --dev
    - run:
        name: "Deploy to Firebase if tests pass and branch is Master"
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build:
    - deploy:
        requires:
        - build
        filters:
          branches:
            only:
            - master
