# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
    environment:
      JEKYLL_ENV: production
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      JOB_RESULTS_PATH: ~/quintsys-web/run-results
    working_directory: ~/quintsys-web
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-gems-{{ .Branch }}-{{ checksum "~/quintsys-web/jekyll/Gemfile.lock" }}
            - v2-gems-{{ .Branch }}
            - v2-gems
      - run:
          name: "Bundle Install"
          command: |
            cd ~/quintsys-web/jekyll
            bundle check || bundle install
      - save_cache:
          key: v2-gems-{{ .Branch }}-{{ checksum "~/quintsys-web/jekyll/Gemfile.lock" }}
          paths:
            - "vendor/bundle"


      - run:
          name: "Create results directory"
          command: mkdir -p $JOB_RESULTS_PATH

      - run:
          name: "Build the Jekyll site"
          command: |
            cd ~/quintsys-web/jekyll
            bundle exec jekyll build 2>&1 | tee $JOB_RESULTS_PATH/build-results.txt

      - run:
          name: "Test with HTMLproofer"
          command: bundle exec htmlproofer ~/quintsys-web/jekyll/_site --check-favicon --check-html --disable-external --empty-alt-ignore | tee $JOB_RESULTS_PATH/htmlproofer-results.txt


      - store_artifacts:
          path: jekyll/_site/
          destination: quintsys-web

      - store_artifacts:
          path: run-results/
          destination: run-results

      - persist_to_workspace:
          root: ~/quintsys-web/jekyll
          paths:
            - _site
  deploy:
    docker:
      - image: circleci/node:10.10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Install firebase-tools"
          command: yarn add firebase-tools --dev
      - run:
          name: "Deploy to Firebase if tests pass and branch is Master"
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
